name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
         pip install --upgrade pip
         pip install poetry
         poetry install -v
         python -c "import cmonge"

      - name: Check formatting
        run: |
         poetry run ruff check .

      - name: Run tests
        run: |
         poetry run pytest -sv cmonge
